### PR TITLE
ES6 iterators

### PR DESCRIPTION
**Pull request by NathanJang**
Adds support for the [iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) in ES6.

### CODE REVIEW

**Comment by flesler** [comment]
Interesting! I'll test it out asap. Would you mind if I squash the 2 commits if I decide to merge it?

**Comment by NathanJang** [comment]
Sure, thanks! I wasn’t sure how to write tests since i’m not sure what environment it’s in.

**Comment by NathanJang** [comment]
Hey! Any update?

**Comment by blitzmann** [comment]
also interested in update... 2 years later... >_>

**Comment by flesler** [comment]
@NathanJang I'd like to get back to this and likely merge. Would you mind adding a couple of tests as well to make sure it all works?

**Comment by NathanJang** [comment]
@flesler I pushed some tests!

**Comment by flesler** [comment]
That looks great! Merging :tada: 
Thank you Nathan

**Comment by flesler** [comment]
[Bumped](https://github.com/flesler/hashmap/commit/5536ab2f1d5a52d953e77cc8c745c18811ad9ead),  [tagged](https://github.com/flesler/hashmap/releases/tag/2.4.0) and [published](https://www.npmjs.com/package/hashmap/v/2.4.0)

**Pull request merged**
