### PR TITLE
Fixing a bug with the `type` method that manifested in minified code

### PR DESCRIPTION
**Pull request by fresheneesz**

### CODE REVIEW

**Comment by flesler** [comment]
Can you provide a reasonable (real life) example where this bug manifests?
Thanks

**Comment by fresheneesz** [comment]
Oops, sorry yeah, I don't even think about semi-colons anymore. 

When I'm trying to squash, I'm getting this:

```
> hashmap@2.0.5-minfiedBugFix prepush D:\billysFile\code\javascript\modules\hashmap
> npm test -- --reporter dot

npm ERR! Error: ENOENT, open 'D:\billysFile\code\javascript\modules\hashmap\node_modules\--reporter\package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "test" "--" "--reporter" "dot"
npm ERR! cwd D:\billysFile\code\javascript\modules\hashmap
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path D:\billysFile\code\javascript\modules\hashmap\node_modules\--reporter\package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\billysFile\code\javascript\modules\hashmap\npm-debug.log
npm ERR! not ok code 0

npm ERR! hashmap@2.0.5-minfiedBugFix prepush: `npm test -- --reporter dot`
npm ERR! Exit status 34
npm ERR!
npm ERR! Failed at the hashmap@2.0.5-minfiedBugFix prepush script.
npm ERR! This is most likely a problem with the hashmap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm test -- --reporter dot
npm ERR! You can get their info via:
npm ERR!     npm owner ls hashmap
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepush"
npm ERR! cwd D:\billysFile\code\javascript\modules\hashmap
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\billysFile\code\javascript\modules\hashmap\npm-debug.log
npm ERR! not ok code 0

husky - pre-push hook failed (add --no-verify to bypass)
```

Honestly, I hate squashing commits with a burning passion. Github doesn't support it, I can never figure it out. Its taking me longer to figure out how to squash this commit than it took me to fix this bug.

**Comment by fresheneesz** [comment]
Ok did I do it?

**Comment by flesler** [comment]
Now you're merging from "Tixit", that's odd.

Do you mind if I just make a new commit with all the changes discussed? I'll mention you in the changelog

**Comment by fresheneesz** [comment]
Sure, that's fine

**Pull request closed without merging**
